name: Build and deploy Node.js docker image - firstmate-git-manager
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    name: validate terraform
    outputs:
      tag: ${{ steps.bump_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - name: validate terraform
        run: cd modules && terraform validate
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: modules/
