repo:
  include:
    - dev-infra-terraform
    - dev-ms-python
    - dev-ms-nodejs
    - dev-weird.char_in-repo]
    - dev-azure_weird.characters
    - ms-python-ai-service
    - ms-nodejs-git-manager
    - demo-*

