repo:
  include:
    - dev-infra-terraform
    - dev-ms-python
    - dev-ms-nodejs
    - dev-weird.char_in-repo
    - ms-python-ai-service
    - ms-nodejs-git-manager
    - demo-microservice
    - demo-microservice-delaware
    - demo-microservice-jeroenh

