repo:
  include:
    - dev-infra-terraform
    - dev-ms-python
    - dev-ms-nodejs
    - dev-weird.char_in-repo]
    - ms-python-ai-service
    - ms-react-platform
    - ms-nodejs-git-manager
    - ms-nodejs-backend
    - ms-nodejs-api-gateway
    - demo-*

