repo:
  include:
    - dev-infra-terraform
    - dev-ms-python
    - dev-ms-nodejs
    - dev-weird.char_in-repo]
    - ms-*
    - demo-*
tools:
  bearer:
    enable: true
    min_severity: 3
  checkov:
    enable: true
    min_severity: 2
