repo:
  include:
    - dev-infra-terraform
    - dev-ms-python
    - dev-ms-nodejs
    - dev-weird.char_in-repo
    - ms-*
    - demo-*
tools:
  Bearer:
    enable: false
    min_severity: 3
  Checkov:
    enable: false
    min_severity: 2
